name: test Artifact

on: push


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: my-artifact.zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /path/to/artifact
